/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type AssetInfo = {
  token: {
    address: Addr;
  };
} | {
  native_token: {
    denom: string;
  };
};
export type Addr = string;
export type Uint128 = string;
export type Decimal = string;
export interface AssetResponse {
  asset_info: AssetInfo;
  oracle_info: AssetOracleInfo[];
}
export interface AssetOracleInfo {
  basket_id: Uint128;
  decimals: number;
  is_usd_par: boolean;
  lp_pool_info?: PoolInfo | null;
  pools_for_osmo_twap: TWAPPoolInfo[];
}
export interface PoolInfo {
  asset_infos: LPAssetInfo[];
  pool_id: number;
}
export interface LPAssetInfo {
  decimals: number;
  info: AssetInfo;
  ratio: Decimal;
}
export interface TWAPPoolInfo {
  base_asset_denom: string;
  pool_id: number;
  quote_asset_denom: string;
}
export type Identifier = string;
export interface Config {
  osmo_usd_pyth_feed_id: Identifier;
  osmosis_proxy_contract?: Addr | null;
  owner: Addr;
  pools_for_usd_par_twap: TWAPPoolInfo[];
  positions_contract?: Addr | null;
  pyth_osmosis_address?: Addr | null;
}
export type ExecuteMsg = {
  update_config: {
    osmo_usd_pyth_feed_id?: Identifier | null;
    osmosis_proxy_contract?: string | null;
    owner?: string | null;
    pools_for_usd_par_twap?: TWAPPoolInfo[] | null;
    positions_contract?: string | null;
    pyth_osmosis_address?: string | null;
  };
} | {
  add_asset: {
    asset_info: AssetInfo;
    oracle_info: AssetOracleInfo;
  };
} | {
  edit_asset: {
    asset_info: AssetInfo;
    oracle_info?: AssetOracleInfo | null;
    remove: boolean;
  };
};
export interface InstantiateMsg {
  osmosis_proxy_contract?: string | null;
  owner?: string | null;
  positions_contract?: string | null;
}
export interface PriceResponse {
  decimals: number;
  price: Decimal;
  prices: PriceInfo[];
}
export interface PriceInfo {
  price: Decimal;
  source: string;
}
export type QueryMsg = {
  config: {};
} | {
  price: {
    asset_info: AssetInfo;
    basket_id?: Uint128 | null;
    oracle_time_limit: number;
    twap_timeframe: number;
  };
} | {
  prices: {
    asset_infos: AssetInfo[];
    oracle_time_limit: number;
    twap_timeframe: number;
  };
} | {
  assets: {
    asset_infos: AssetInfo[];
  };
};