/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./LiquidationQueue.types";
import * as _1 from "./LiquidationQueue.client";
import * as _2 from "./LiquidationQueue.message-composer";
export namespace contracts {
  export const LiquidationQueue = { ..._0,
    ..._1,
    ..._2
  };
}